"""Item and item_size tables update

Revision ID: fbf1d6a44529
Revises: bcde0e9c46de
Create Date: 2024-12-24 14:41:19.671170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf1d6a44529'
down_revision: Union[str, None] = 'bcde0e9c46de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('item_size', 'description')
    op.drop_constraint('item_size_pkey', 'item_size')
    op.create_primary_key('item_size_pkey', 'item_size', ['item_id', 'size'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_size', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('item', 'description')
    op.create_primary_key('item_size_pkey', 'item_size', ['item_id', 'image'])
    op.drop_constraint('item_size_pkey', 'item_size')
    # ### end Alembic commands ###
