"""item_size table + item update

Revision ID: bcde0e9c46de
Revises: 11df913a3645
Create Date: 2024-12-23 08:37:15.568011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcde0e9c46de'
down_revision: Union[str, None] = '11df913a3645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_size',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'image')
    )
    op.drop_column('item', 'image')
    op.drop_column('item', 'size')
    op.drop_column('item', 'description')
    op.drop_column('item', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('item', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('item', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('item', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('item_size')
    # ### end Alembic commands ###
