"""item_type table

Revision ID: 11df913a3645
Revises: bf1fa89cddfc
Create Date: 2024-12-01 13:20:46.339871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11df913a3645'
down_revision: Union[str, None] = 'bf1fa89cddfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_type',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_type')
    # ### end Alembic commands ###
