"""added cascade on update to tables

Revision ID: 18465c8ecfce
Revises: 2e6fefccaa35
Create Date: 2025-01-07 19:50:31.217699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18465c8ecfce'
down_revision: Union[str, None] = '2e6fefccaa35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_size_item_id_fkey', 'item_size', type_='foreignkey')
    op.create_foreign_key(None, 'item_size', 'item', ['item_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('item_type_type_id_fkey', 'item_type', type_='foreignkey')
    op.drop_constraint('item_type_item_id_fkey', 'item_type', type_='foreignkey')
    op.create_foreign_key(None, 'item_type', 'item', ['item_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'item_type', 'type', ['type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('type_category_id_fkey', 'type', type_='foreignkey')
    op.create_foreign_key(None, 'type', 'category', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'type', type_='foreignkey')
    op.create_foreign_key('type_category_id_fkey', 'type', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'item_type', type_='foreignkey')
    op.drop_constraint(None, 'item_type', type_='foreignkey')
    op.create_foreign_key('item_type_item_id_fkey', 'item_type', 'item', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('item_type_type_id_fkey', 'item_type', 'type', ['type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'item_size', type_='foreignkey')
    op.create_foreign_key('item_size_item_id_fkey', 'item_size', 'item', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
